const ENDPOINTS = {
    TRENDING: '/trending/all/day',
    TRENDING_MOVIES: '/trending/movie/day',
    TRENDING_TV: '/trending/tv/day',
    POPULAR_MOVIES: '/movie/popular',
    TOP_RATED_MOVIES: '/movie/top_rated',
    UPCOMING_MOVIES: '/movie/upcoming',
    NOW_PLAYING_MOVIES: '/movie/now_playing',
    TV_SHOWS: '/tv/popular',
    TV_TOP_RATED: '/tv/top_rated',
    TV_AIRING_TODAY: '/tv/airing_today',
    TV_ON_THE_AIR: '/tv/on_the_air',
    MOVIE_DETAILS: (id) => `/movie/${id}`,
    MOVIE_CREDITS: (id) => `/movie/${id}/credits`,
    SIMILAR_MOVIES: (id) => `/movie/${id}/similar`,
    SEARCH: '/search/multi',
    DISCOVER_MOVIE: '/discover/movie',
    DISCOVER_TV: '/discover/tv',
    TV_DETAILS: (id) => `/tv/${id}`,
    TV_CREDITS: (id) => `/tv/${id}/credits`,
    TV_SEASON_DETAILS: (id, seasonNumber) => `/tv/${id}/season/${seasonNumber}`,
    SIMILAR_TV_SHOWS: (id) => `/tv/${id}/similar`,
    MOVIE_IMAGES: (id) => `/movie/${id}/images`,
    MOVIE_VIDEOS: (id) => `/movie/${id}/videos`,
    TV_IMAGES: (id) => `/tv/${id}/images`,
    IMAGE_BASE_URL: 'https://image.tmdb.org/t/p/w1280',
    IMAGE_BASE_URL_W500: 'https://image.tmdb.org/t/p/w500',
    IMAGE_BASE_URL_W780: 'https://image.tmdb.org/t/p/w780',
    IMAGE_BASE_URL_W1280: 'https://image.tmdb.org/t/p/w1280',
};

export default ENDPOINTS;
