-- 1. Create Profiles Table (Linked to Auth Users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- 2. Create My List Table
create table my_list (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  media_id integer not null, -- TMDB ID
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  poster_path text,
  backdrop_path text,
  vote_average numeric,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, media_id, media_type) -- Prevent duplicates
);

-- 3. Create Watch History Table
create table watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  media_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  poster_path text,
  backdrop_path text,
  duration integer, -- Total duration in seconds
  watched integer, -- Watched duration in seconds
  last_watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, media_id, media_type)
);

-- 4. Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table my_list enable row level security;
alter table watch_history enable row level security;

-- 5. Create Policies
-- Profiles: Public can view, User can update own
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- My List: Users can only see and edit their own list
create policy "Users can view own list." on my_list for select using ( auth.uid() = user_id );
create policy "Users can insert into own list." on my_list for insert with check ( auth.uid() = user_id );
create policy "Users can delete from own list." on my_list for delete using ( auth.uid() = user_id );

-- Watch History: Users can only see and edit their own history
create policy "Users can view own history." on watch_history for select using ( auth.uid() = user_id );
create policy "Users can insert into own history." on watch_history for insert with check ( auth.uid() = user_id );
create policy "Users can update own history." on watch_history for update using ( auth.uid() = user_id );

-- 6. Trigger for Profile Creation on Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
